function T = T(in1,L_0)
%T
%    T = T(IN1,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:49:22

deltaL = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = phi.^2;
t4 = theta.^2;
t5 = t3+t4;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t9 = cos(t7);
t10 = sin(t7);
t11 = t9-1.0;
t12 = phi.*t8.*t10;
t13 = t8.*t10.*theta;
t14 = phi.*t6.*t11.*theta;
T = reshape([t4.*t6.*t11+1.0,t14,-t13,0.0,t14,t3.*t6.*t11+1.0,-t12,0.0,t13,t12,t9,0.0,-t2.*t6.*t11.*theta,-phi.*t2.*t6.*t11,t2.*t8.*t10,1.0],[4,4]);
end
