function v_i_1_i = v_rel(in1,in2,L_0)
%V_REL
%    V_I_1_I = V_REL(IN1,IN2,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:49:23

ddeltaL = in2(3,:);
deltaL = in1(3,:);
dphi = in2(2,:);
dtheta = in2(1,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = phi.^2;
t4 = theta.^2;
t5 = t3+t4;
t6 = 1.0./t5;
t8 = sqrt(t5);
t7 = t6.^2;
t9 = 1.0./t8.^3;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t14 = phi.*t2.*t9.*t11.*theta;
t13 = t2.*t6.*t12;
t16 = phi.*t2.*t7.*t12.*theta.*2.0;
t15 = -t13;
t17 = t14+t16;
v_i_1_i = [dphi.*t17+dtheta.*(t15+t2.*t4.*t7.*t12.*2.0+t2.*t4.*t9.*t11)-ddeltaL.*t6.*t12.*theta;dtheta.*t17+dphi.*(t15+t2.*t3.*t7.*t12.*2.0+t2.*t3.*t9.*t11)-ddeltaL.*phi.*t6.*t12;dphi.*(phi.*t2.*t6.*t10-phi.*t2.*t9.*t11)+dtheta.*(t2.*t6.*t10.*theta-t2.*t9.*t11.*theta)+(ddeltaL.*t11)./t8];
end
