function dv_i_1_i = a_rel(in1,in2,in3,L_0)
%A_REL
%    DV_I_1_I = A_REL(IN1,IN2,IN3,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:45

dddeltaL = in3(2,:);
ddeltaL = in2(2,:);
ddtheta = in3(1,:);
deltaL = in1(2,:);
dtheta = in2(1,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0+deltaL;
t7 = 1.0./theta;
t5 = t2.*theta;
t6 = t3.*theta;
t8 = t7.^2;
t9 = t7.^3;
t10 = t2-1.0;
t11 = -t5;
t13 = t6+t10;
t12 = t3+t11;
dv_i_1_i = [dtheta.*(ddeltaL.*t2.*t7-ddeltaL.*t3.*t8-dtheta.*t3.*t4.*t7+dtheta.*t4.*t9.*t12.*2.0)+dddeltaL.*t3.*t7-ddeltaL.*dtheta.*t8.*t12-ddtheta.*t4.*t8.*t12;dtheta.*(ddeltaL.*t3.*t7+ddeltaL.*t8.*t10+dtheta.*t2.*t4.*t7-dtheta.*t4.*t9.*t13.*2.0)-dddeltaL.*t7.*t10+ddeltaL.*dtheta.*t8.*t13+ddtheta.*t4.*t8.*t13;0.0];
end
