function domega_i_1_i = domega_rel(in1,in2,in3,L_0)
%DOMEGA_REL
%    DOMEGA_I_1_I = DOMEGA_REL(IN1,IN2,IN3,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

ddtheta = in3(1,:);
domega_i_1_i = [0.0;0.0;ddtheta];
end
