function omega_i_1_i = omega_rel(in1,in2,L_0)
%OMEGA_REL
%    OMEGA_I_1_I = OMEGA_REL(IN1,IN2,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:45

dtheta = in2(1,:);
omega_i_1_i = [0.0;0.0;dtheta];
end
