function omega_par_i = omega_par(in1,L_0)
%OMEGA_PAR
%    OMEGA_PAR_I = OMEGA_PAR(IN1,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

omega_par_i = reshape([0.0,0.0,1.0,0.0,0.0,0.0],[3,2]);
end
