function T_s = T_s(in1,in2,s)
%T_s
%    T_s = T_s(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:45

L_0 = in2(1,:);
deltaL = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = 1.0./L_0;
t4 = 1.0./theta;
t5 = s.*t3.*theta;
t6 = cos(t5);
t7 = sin(t5);
T_s = reshape([t6,t7,0.0,0.0,-t7,t6,0.0,0.0,0.0,0.0,1.0,0.0,t2.*t4.*t7,-t2.*t4.*(t6-1.0),0.0,1.0],[4,4]);
end
