function v_par_i = v_par(in1,L_0)
%V_PAR
%    V_PAR_I = V_PAR(IN1,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

deltaL = in1(2,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0+deltaL;
t7 = 1.0./theta;
t5 = t2.*theta;
t6 = t3.*theta;
t8 = t7.^2;
t9 = t2-1.0;
t10 = -t5;
t12 = t6+t9;
t11 = t3+t10;
v_par_i = reshape([-t2.*t4.*t8.*t11+t3.*t4.*t8.*t12,t2.*t4.*t8.*t12+t3.*t4.*t8.*t11,0.0,t2.*t3.*t7-t3.*t7.*t9,-t3.^2.*t7-t2.*t7.*t9,0.0],[3,2]);
end
