function v_i_1_i = v_rel(in1,in2,L_0)
%V_REL
%    V_I_1_I = V_REL(IN1,IN2,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:45

ddeltaL = in2(2,:);
deltaL = in1(2,:);
dtheta = in2(1,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0+deltaL;
t5 = 1.0./theta;
t6 = t5.^2;
v_i_1_i = [ddeltaL.*t3.*t5-dtheta.*t4.*t6.*(t3-t2.*theta);-ddeltaL.*t5.*(t2-1.0)+dtheta.*t4.*t6.*(t2+t3.*theta-1.0);0.0];
end
