function D_s = D_s(in1,in2,in3,s)
%D_s
%    D_s = D_s(IN1,IN2,IN3,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:59:27

E_mod = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
Poi = in3(5,:);
R = in3(2,:);
ddeltaL = in2(6,:);
dgamma_X = in2(4,:);
dgamma_Y = in2(5,:);
dkappa_X = in2(1,:);
dkappa_Y = in2(2,:);
dtau_Z = in2(3,:);
t2 = Poi.*2.0;
t3 = R.^2;
t5 = 1.0./L_0.^2;
t4 = t3.^2;
t6 = t2+2.0;
t7 = 1.0./t6;
D_s = [(E_mod.*Eta.*dkappa_X.*t4.*t5.*pi)./4.0;(E_mod.*Eta.*dkappa_Y.*t4.*t5.*pi)./4.0;(E_mod.*Eta.*dtau_Z.*t4.*t5.*t7.*pi)./2.0;E_mod.*Eta.*dgamma_X.*t3.*t5.*t7.*pi;E_mod.*Eta.*dgamma_Y.*t3.*t5.*t7.*pi;E_mod.*Eta.*ddeltaL.*t3.*t5.*pi];
end
