function xi_i = xi(in1,in2,s)
%XI
%    XI_I = XI(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:59:39

L_0 = in2(1,:);
deltaL = in1(6,:);
gamma_X = in1(4,:);
gamma_Y = in1(5,:);
kappa_X = in1(1,:);
kappa_Y = in1(2,:);
tau_Z = in1(3,:);
t2 = 1.0./L_0;
xi_i = [-kappa_Y.*t2;kappa_X.*t2;t2.*tau_Z;gamma_X.*t2;gamma_Y.*t2;t2.*(L_0+deltaL)];
end
