function omega_par_i = omega_par(theta,L_0)
%OMEGA_PAR
%    OMEGA_PAR_I = OMEGA_PAR(THETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:45

omega_par_i = [0.0;-1.0;0.0];
end
