function v_i_1_i = v_rel(theta,dtheta,L_0)
%V_REL
%    V_I_1_I = V_REL(THETA,DTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:45

t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./theta.^2;
v_i_1_i = [-L_0.*dtheta.*t4.*(t2+t3.*theta-1.0);0.0;-L_0.*dtheta.*t4.*(t3-t2.*theta)];
end
