function dv_i_comi = a_com_rel(in1,in2,in3,in4)
%A_COM_REL
%    DV_I_COMI = A_COM_REL(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

L_0 = in4(1,:);
dddeltaL = in3(2,:);
ddeltaL = in2(2,:);
ddtheta = in3(1,:);
deltaL = in1(2,:);
dtheta = in2(1,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0+deltaL;
t5 = 1.0./theta.^2;
t6 = 1.0./theta.^3;
t7 = t5.^2;
t8 = t2-1.0;
t11 = t3.*t4.*t5;
dv_i_comi = [-ddtheta.*(t11+t4.*t6.*t8.*2.0)-dtheta.*(-dtheta.*(-t2.*t4.*t5+t3.*t4.*t6.*4.0+t4.*t7.*t8.*6.0)+ddeltaL.*t3.*t5+ddeltaL.*t6.*t8.*2.0)-ddeltaL.*dtheta.*(t3.*t5+t6.*t8.*2.0)+dddeltaL.*t5.*t8;-ddtheta.*(t4.*t5.*t8-t4.*t6.*(t3-theta).*2.0)+dtheta.*(dtheta.*(t11+t4.*t6.*t8.*4.0-t4.*t7.*(t3-theta).*6.0)-ddeltaL.*t5.*t8+ddeltaL.*t6.*(t3-theta).*2.0)-ddeltaL.*dtheta.*(t5.*t8-t6.*(t3-theta).*2.0)-dddeltaL.*t5.*(t3-theta);0.0];
end
