function D_q = D(in1,in2,in3)
%D
%    D_q = D(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:47

E = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
Poi = in3(5,:);
R = in3(2,:);
ddeltaL = in2(2,:);
dtheta = in2(1,:);
t2 = 1.0./L_0;
D_q = [(E.*Eta.*R.^4.*dtheta.*t2.*pi)./(Poi.*4.0+4.0);(E.*Eta.*R.^2.*ddeltaL.*t2.*pi)./(Poi.*2.0+2.0)];
end
