function grad_int_r_i_X_dr_i = grad_int_r_X_dr(in1,in2)
%grad_int_r_X_dr
%    grad_int_r_i_X_dr_i = grad_int_r_X_dr(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:47

L_0 = in2(1,:);
R = in2(2,:);
deltaL = in1(2,:);
rho = in2(3,:);
theta = in1(1,:);
grad_int_r_i_X_dr_i = reshape([0.0,0.0,0.0,0.0,L_0.*R.^2.*rho.*1.0./theta.^4.*pi.*(L_0+deltaL).^2.*(cos(theta).*2.0+theta.^2-2.0).*(-1.0./2.0),0.0],[2,3]);
end
