function grad_J = grad_J(in1,in2)
%grad_J
%    grad_J = grad_J(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:47

L_0 = in2(1,:);
R = in2(2,:);
deltaL = in1(2,:);
rho = in2(3,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0.^2;
t5 = L_0.^3;
t6 = R.^2;
t7 = deltaL.^2;
t8 = theta.*2.0;
t9 = theta.^2;
t13 = 1.0./theta.^3;
t15 = 1.0./theta.^5;
t17 = theta./2.0;
t10 = cos(t8);
t11 = sin(t8);
t12 = t3.^2;
t14 = 1.0./t9.^2;
t16 = t2-1.0;
t19 = sin(t17);
t23 = (L_0.*t9)./2.0;
t30 = deltaL.*rho.*t4.*t6.*theta.*pi.*3.0;
t32 = rho.*t3.*t5.*t6.*pi.*8.0;
t33 = rho.*t2.*t5.*t6.*t8.*pi;
t34 = rho.*t5.*t6.*theta.*pi.*(3.0./2.0);
t36 = L_0.*rho.*t2.*t6.*t7.*t8.*pi;
t37 = deltaL.*rho.*t2.*t4.*t6.*theta.*pi.*4.0;
t38 = L_0.*rho.*t6.*t7.*theta.*pi.*(3.0./2.0);
t40 = L_0.*rho.*t3.*t6.*t7.*pi.*8.0;
t41 = deltaL.*rho.*t3.*t4.*t6.*pi.*1.6e+1;
t20 = t12.*2.0;
t21 = L_0.*t12;
t24 = t10./2.0;
t25 = t19.^2;
t28 = (L_0.*t11.*theta)./4.0;
t39 = rho.*t5.*t6.*t11.*pi.*4.0;
t44 = L_0.*rho.*t6.*t7.*t11.*pi.*4.0;
t50 = deltaL.*rho.*t4.*t6.*t11.*pi.*8.0;
t51 = deltaL.*rho.*t4.*t6.*t10.*theta.*pi.*7.0;
t52 = rho.*t5.*t6.*t9.*t11.*pi;
t55 = rho.*t5.*t6.*t10.*theta.*pi.*(7.0./2.0);
t56 = rho.*t4.*t6.*t12.*t13.*pi;
t57 = L_0.*rho.*t6.*t7.*t9.*t11.*pi;
t58 = L_0.*rho.*t6.*t7.*t10.*theta.*pi.*(7.0./2.0);
t62 = L_0.*deltaL.*rho.*t3.*t6.*t14.*t16.*pi.*2.0;
t63 = rho.*t3.*t4.*t6.*t14.*t16.*pi.*2.0;
t26 = -t21;
t29 = t25.*8.0;
t35 = t24-1.0./2.0;
t61 = -t56;
t64 = -t62;
t65 = -t63;
t71 = (t15.*(t30-t32+t33+t34+t36+t37+t38+t39-t40-t41+t44+t50-t51-t52-t55-t57-t58-deltaL.*rho.*t4.*t6.*t9.*t11.*pi.*2.0))./2.0;
t59 = deltaL.*rho.*t6.*t13.*t26.*pi;
t66 = t23+t26+t28;
t68 = t59+t61+t64+t65;
grad_J = reshape([rho.*t5.*t6.*t13.*pi.*(-1.0./2.0)-(L_0.*rho.*t6.*t7.*t13.*pi)./2.0-deltaL.*rho.*t4.*t6.*t13.*pi-rho.*t5.*t6.*t11.*t14.*pi.*(7.0./4.0)+rho.*t5.*t6.*t13.*t35.*pi-rho.*t5.*t6.*t15.*t35.*pi.*4.0-L_0.*rho.*t6.*t7.*t11.*t14.*pi.*(7.0./4.0)+L_0.*rho.*t6.*t7.*t13.*t35.*pi-L_0.*rho.*t6.*t7.*t15.*t35.*pi.*4.0-deltaL.*rho.*t4.*t6.*t11.*t14.*pi.*(7.0./2.0)+deltaL.*rho.*t4.*t6.*t13.*t35.*pi.*2.0-deltaL.*rho.*t4.*t6.*t15.*t35.*pi.*8.0,t71,0.0,t71,t15.*(rho.*t5.*t6.*pi.*-1.2e+1-L_0.*rho.*t6.*t7.*pi.*1.2e+1-deltaL.*rho.*t4.*t6.*pi.*2.4e+1+rho.*t2.*t5.*t6.*pi.*1.6e+1-rho.*t5.*t6.*t10.*pi.*4.0+L_0.*rho.*t2.*t6.*t7.*pi.*1.6e+1-L_0.*rho.*t6.*t7.*t10.*pi.*4.0+deltaL.*rho.*t2.*t4.*t6.*pi.*3.2e+1+deltaL.*rho.*t4.*t6.*t9.*pi.*4.0-deltaL.*rho.*t4.*t6.*t10.*pi.*8.0+rho.*t5.*t6.*t9.*t10.*pi+rho.*t3.*t5.*t6.*theta.*pi.*4.0+rho.*t5.*t6.*t8.*theta.*pi-rho.*t5.*t6.*t11.*theta.*pi.*(7.0./2.0)+L_0.*rho.*t6.*t7.*t9.*t10.*pi+L_0.*rho.*t3.*t6.*t7.*theta.*pi.*4.0+L_0.*rho.*t6.*t7.*t8.*theta.*pi-L_0.*rho.*t6.*t7.*t11.*theta.*pi.*(7.0./2.0)+deltaL.*rho.*t3.*t4.*t6.*theta.*pi.*8.0-deltaL.*rho.*t4.*t6.*t11.*theta.*pi.*7.0+deltaL.*rho.*t4.*t6.*t8.*t10.*theta.*pi).*(-1.0./2.0),0.0,0.0,0.0,rho.*t5.*t6.*t13.*pi.*-2.0+rho.*t5.*t6.*t15.*pi.*8.0-L_0.*rho.*t6.*t7.*t13.*pi.*2.0+L_0.*rho.*t6.*t7.*t15.*pi.*8.0-deltaL.*rho.*t4.*t6.*t13.*pi.*4.0+deltaL.*rho.*t4.*t6.*t15.*pi.*1.6e+1-rho.*t2.*t5.*t6.*t15.*pi.*8.0-rho.*t3.*t5.*t6.*t14.*pi.*2.0-L_0.*rho.*t2.*t6.*t7.*t15.*pi.*8.0-L_0.*rho.*t3.*t6.*t7.*t14.*pi.*2.0-deltaL.*rho.*t2.*t4.*t6.*t15.*pi.*1.6e+1-deltaL.*rho.*t3.*t4.*t6.*t14.*pi.*4.0,L_0.*rho.*t6.*t14.*t66.*pi.*2.0+deltaL.*rho.*t6.*t14.*t66.*pi.*2.0,t68,0.0,t68,rho.*t4.*t6.*t14.*pi.*(t9+t20-t29-(t11.*theta)./2.0)+L_0.*deltaL.*rho.*t6.*t14.*pi.*(t9+t20-t29-(t11.*theta)./2.0),0.0,0.0,0.0,t14.*(t9.*(rho.*t4.*t6.*pi.*2.0+L_0.*deltaL.*rho.*t6.*pi.*2.0)-rho.*t4.*t6.*pi.*4.0-L_0.*deltaL.*rho.*t6.*pi.*4.0+rho.*t2.*t4.*t6.*pi.*4.0+L_0.*deltaL.*rho.*t2.*t6.*pi.*4.0)],[3,3,2]);
end
