function int_dr_i_X_pv_r = int_dr_X_pv_r(in1,in2,in3)
%int_dr_X_pv_r
%    int_dr_i_X_pv_r = int_dr_X_pv_r(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:47

L_0 = in3(1,:);
R = in3(2,:);
ddeltaL = in2(2,:);
deltaL = in1(2,:);
dtheta = in2(1,:);
rho = in3(3,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = L_0+deltaL;
t4 = R.^2;
t5 = theta.^2;
t6 = t2.*2.0;
t7 = 1.0./t5.^2;
t8 = t5+t6-2.0;
int_dr_i_X_pv_r = reshape([0.0,0.0,0.0,0.0,L_0.*ddeltaL.*rho.*t3.*t4.*t7.*t8.*pi.*(-1.0./2.0),(L_0.*dtheta.*rho.*t3.*t4.*t7.*t8.*pi)./2.0],[2,3]);
end
