function int_r_i_X_ddr_i = int_r_X_ddr(in1,in2,in3,in4)
%int_r_X_ddr
%    int_r_i_X_ddr_i = int_r_X_ddr(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

L_0 = in4(1,:);
R = in4(2,:);
ddeltaL = in2(2,:);
ddtheta = in3(1,:);
deltaL = in1(2,:);
dtheta = in2(1,:);
rho = in4(3,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
t5 = theta.^2;
t6 = theta.^3;
int_r_i_X_ddr_i = [0.0;0.0;(L_0.*R.^2.*rho.*1.0./theta.^5.*pi.*(L_0+deltaL).*(L_0.*t4.*-8.0-deltaL.*t4.*8.0-L_0.*ddtheta.*t6+L_0.*ddtheta.*theta.*2.0+L_0.*t2.*t4.*8.0+L_0.*t4.*t5.*2.0-ddtheta.*deltaL.*t6-ddeltaL.*dtheta.*t6.*2.0+ddtheta.*deltaL.*theta.*2.0+ddeltaL.*dtheta.*theta.*4.0+deltaL.*t2.*t4.*8.0+deltaL.*t4.*t5.*2.0+L_0.*t3.*t4.*theta.*2.0-ddtheta.*deltaL.*t2.*theta.*2.0-ddeltaL.*dtheta.*t2.*theta.*4.0+deltaL.*t3.*t4.*theta.*2.0-L_0.*ddtheta.*t2.*theta.*2.0))./2.0];
end
