function J = J(in1,in2,in3)
%J
%    J = J(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

L_0 = in3(1,:);
R = in3(2,:);
ddeltaL = in2(2,:);
deltaL = in1(2,:);
dtheta = in2(1,:);
rho = in3(3,:);
theta = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0+deltaL;
t5 = R.^2;
t6 = theta.*2.0;
t7 = theta.^2;
t8 = theta.^3;
t12 = 1.0./theta.^5;
t13 = L_0.*dtheta.*theta.*3.0;
t14 = deltaL.*dtheta.*theta.*3.0;
t9 = cos(t6);
t10 = sin(t6);
t11 = t3.^2;
t16 = ddeltaL.*t6.*theta;
t18 = L_0.*dtheta.*t7;
t19 = deltaL.*dtheta.*t7;
t20 = deltaL.*dtheta.*t3.*1.6e+1;
t21 = ddeltaL.*t3.*theta.*8.0;
t22 = L_0.*dtheta.*t2.*theta.*4.0;
t23 = deltaL.*dtheta.*t2.*theta.*4.0;
t24 = L_0.*dtheta.*t3.*1.6e+1;
t28 = ddeltaL.*t10.*theta.*4.0;
t29 = L_0.*dtheta.*t10.*8.0;
t30 = deltaL.*dtheta.*t10.*8.0;
t31 = L_0.*dtheta.*t9.*theta.*7.0;
t32 = deltaL.*dtheta.*t9.*theta.*7.0;
t36 = L_0.*dtheta.*t6.*t10.*theta;
t37 = deltaL.*dtheta.*t6.*t10.*theta;
t41 = (L_0.*rho.*t4.*t5.*t12.*pi.*(t13+t14-t16-t20+t21+t22+t23-t24-t28+t29+t30-t31-t32-t36-t37+ddeltaL.*t7.*t9.*2.0))./4.0;
mt1 = [L_0.*rho.*t4.*t5.*t12.*pi.*(t18+t19-ddeltaL.*t8.*2.0-L_0.*dtheta.*t11.*8.0-deltaL.*dtheta.*t11.*8.0-ddeltaL.*t7.*t10+ddeltaL.*t11.*theta.*4.0+deltaL.*dtheta.*t10.*theta.*(7.0./2.0)+L_0.*dtheta.*t10.*theta.*(7.0./2.0)+L_0.*dtheta.*t6.*t11.*theta+deltaL.*dtheta.*t6.*t11.*theta).*(-1.0./2.0),t41,0.0,t41,L_0.*rho.*t4.*t5.*t12.*pi.*(t18.*4.0+t19.*4.0-L_0.*dtheta.*2.4e+1-deltaL.*dtheta.*2.4e+1-ddeltaL.*t8.*4.0+ddeltaL.*theta.*1.2e+1+t10.*t16+L_0.*dtheta.*t2.*3.2e+1-L_0.*dtheta.*t9.*8.0+deltaL.*dtheta.*t2.*3.2e+1-deltaL.*dtheta.*t9.*8.0-ddeltaL.*t2.*theta.*1.6e+1+ddeltaL.*t9.*theta.*4.0+deltaL.*dtheta.*t3.*theta.*8.0-deltaL.*dtheta.*t10.*theta.*7.0+L_0.*dtheta.*t3.*theta.*8.0-L_0.*dtheta.*t10.*theta.*7.0+L_0.*dtheta.*t6.*t9.*theta+deltaL.*dtheta.*t6.*t9.*theta).*(-1.0./4.0),0.0,0.0,0.0];
mt2 = [L_0.*rho.*t4.*t5.*t12.*pi.*(t18+t19-L_0.*dtheta.*4.0-deltaL.*dtheta.*4.0+ddeltaL.*t6-ddeltaL.*t8+L_0.*dtheta.*t2.*4.0+deltaL.*dtheta.*t2.*4.0-ddeltaL.*t2.*theta.*2.0+deltaL.*dtheta.*t3.*theta+L_0.*dtheta.*t3.*theta).*-2.0];
J = reshape([mt1,mt2],3,3);
end
