function K_q = K(in1,in2)
%K
%    K_q = K(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:47

E = in2(4,:);
L_0 = in2(1,:);
Poi = in2(5,:);
R = in2(2,:);
deltaL = in1(2,:);
theta = in1(1,:);
t2 = 1.0./L_0;
K_q = [(E.*R.^4.*t2.*theta.*pi)./(Poi.*4.0+4.0);(E.*R.^2.*deltaL.*t2.*pi)./(Poi.*2.0+2.0)];
end
