function p_comi = p_com(in1,in2)
%P_COM
%    P_COMI = P_COM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:46

L_0 = in2(1,:);
deltaL = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = 1.0./theta.^2;
p_comi = [t2.*t3.*(cos(theta)-1.0);t2.*t3.*(theta-sin(theta));0.0];
end
