function xi_i = xi(in1,in2,s)
%XI
%    XI_I = XI(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:47:47

L_0 = in2(1,:);
deltaL = in1(2,:);
theta = in1(1,:);
t2 = 1.0./L_0;
xi_i = [0.0;0.0;t2.*theta;t2.*(L_0+deltaL);0.0;0.0];
end
