function D_q = D(in1,in2,in3)
%D
%    D_q = D(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:10

E = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
R = in3(2,:);
ddeltaL = in2(3,:);
dphi = in2(2,:);
dtheta = in2(1,:);
t2 = R.^4;
t3 = 1.0./L_0;
D_q = [E.*Eta.*dtheta.*t2.*t3.*pi.*2.500000000000111e-1;E.*Eta.*dphi.*t2.*t3.*pi.*2.500000000000111e-1;E.*Eta.*R.^2.*ddeltaL.*t3.*pi.*1.000000000000044];
end
