function grad_v_com_i = grad_v_com(in1,in2)
%GRAD_V_COM
%    GRAD_V_COM_I = GRAD_V_COM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:10

L_0 = in2(1,:);
deltaL = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = phi.^2;
t4 = phi.^3;
t5 = theta.^2;
t6 = theta.^3;
t7 = t3+t5;
t8 = 1.0./t7;
t11 = sqrt(t7);
t9 = t8.^2;
t10 = t8.^3;
t12 = 1.0./t11;
t15 = cos(t11);
t16 = sin(t11);
t13 = t12.^3;
t14 = t12.^5;
t17 = phi.*t12;
t18 = t12.*theta;
t20 = t15-1.0;
t21 = t15.*t17;
t22 = t15.*t18;
t29 = t2.*t13.*(t11-t16);
t30 = phi.*t2.*t14.*theta.*(t11-t16).*-3.0;
t24 = -t21;
t25 = -t22;
t26 = t17+t24;
t27 = t18+t25;
mt1 = [t29+t2.*t13.*t27.*theta-t2.*t5.*t14.*(t11-t16).*3.0,t30+t2.*t13.*t26.*theta,t13.*theta.*(t11-t16),t30+phi.*t2.*t13.*t27,t29+phi.*t2.*t13.*t26-t2.*t3.*t14.*(t11-t16).*3.0,phi.*t13.*(t11-t16),-t2.*t8.*t15.*theta+t2.*t13.*t16.*theta+t2.*t3.*t9.*t16.*t27+t2.*t5.*t9.*t16.*t27+t2.*t9.*t15.*t20.*theta.*2.0+t2.*t13.*t15.*t16.*theta+t2.*t13.*t16.*t20.*theta-t2.*t6.*t10.*t16.*(t11-t16).*4.0+t2.*t6.*t14.*t15.*(t11-t16)+t2.*t9.*t16.*theta.*(t11-t16).*2.0-t2.*t3.*t10.*t16.*theta.*(t11-t16).*4.0+t2.*t3.*t14.*t15.*theta.*(t11-t16)];
mt2 = [-phi.*t2.*t8.*t15+phi.*t2.*t13.*t16+phi.*t2.*t9.*t15.*t20.*2.0+phi.*t2.*t13.*t15.*t16+phi.*t2.*t13.*t16.*t20+t2.*t3.*t9.*t16.*t26+t2.*t5.*t9.*t16.*t26+phi.*t2.*t9.*t16.*(t11-t16).*2.0-t2.*t4.*t10.*t16.*(t11-t16).*4.0+t2.*t4.*t14.*t15.*(t11-t16)-phi.*t2.*t5.*t10.*t16.*(t11-t16).*4.0+phi.*t2.*t5.*t14.*t15.*(t11-t16),-t12.*t16-t8.*t15.*t20+t3.*t9.*t16.*(t11-t16)+t5.*t9.*t16.*(t11-t16)];
grad_v_com_i = reshape([mt1,mt2],3,3);
end
