function v_i_comi = v_com_rel(in1,in2,in3)
%V_COM_REL
%    V_I_COMI = V_COM_REL(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:49:25

L_0 = in3(1,:);
ddeltaL = in2(3,:);
deltaL = in1(3,:);
dphi = in2(2,:);
dtheta = in2(1,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = phi.^2;
t4 = phi.^3;
t5 = theta.^2;
t6 = theta.^3;
t7 = t3+t5;
t8 = 1.0./t7;
t11 = sqrt(t7);
t9 = t8.^2;
t10 = t8.^3;
t12 = 1.0./t11;
t15 = cos(t11);
t16 = sin(t11);
t13 = t12.^3;
t14 = t12.^5;
t17 = phi.*t12;
t18 = t12.*theta;
t20 = t15-1.0;
t21 = t15.*t17;
t22 = t15.*t18;
t29 = t2.*t13.*(t11-t16);
t30 = phi.*t2.*t14.*theta.*(t11-t16).*-3.0;
t24 = -t21;
t25 = -t22;
t26 = t17+t24;
t27 = t18+t25;
et1 = dphi.*(-phi.*t2.*t8.*t15+phi.*t2.*t13.*t16+phi.*t2.*t9.*t15.*t20.*2.0+phi.*t2.*t13.*t15.*t16+phi.*t2.*t13.*t16.*t20+t2.*t3.*t9.*t16.*t26+t2.*t5.*t9.*t16.*t26+phi.*t2.*t9.*t16.*(t11-t16).*2.0-t2.*t4.*t10.*t16.*(t11-t16).*4.0+t2.*t4.*t14.*t15.*(t11-t16)-phi.*t2.*t5.*t10.*t16.*(t11-t16).*4.0+phi.*t2.*t5.*t14.*t15.*(t11-t16));
et2 = dtheta.*(-t2.*t8.*t15.*theta+t2.*t13.*t16.*theta+t2.*t3.*t9.*t16.*t27+t2.*t5.*t9.*t16.*t27+t2.*t9.*t15.*t20.*theta.*2.0+t2.*t13.*t15.*t16.*theta+t2.*t13.*t16.*t20.*theta-t2.*t6.*t10.*t16.*(t11-t16).*4.0+t2.*t6.*t14.*t15.*(t11-t16)+t2.*t9.*t16.*theta.*(t11-t16).*2.0-t2.*t3.*t10.*t16.*theta.*(t11-t16).*4.0+t2.*t3.*t14.*t15.*theta.*(t11-t16))-ddeltaL.*(t12.*t16+t8.*t15.*t20-t3.*t9.*t16.*(t11-t16)-t5.*t9.*t16.*(t11-t16));
v_i_comi = [dtheta.*(t29+t2.*t13.*t27.*theta-t2.*t5.*t14.*(t11-t16).*3.0)+dphi.*(t30+t2.*t13.*t26.*theta)+ddeltaL.*t13.*theta.*(t11-t16);dphi.*(t29+phi.*t2.*t13.*t26-t2.*t3.*t14.*(t11-t16).*3.0)+dtheta.*(t30+phi.*t2.*t13.*t27)+ddeltaL.*phi.*t13.*(t11-t16);et1+et2];
end
