function xi_i = xi(in1,in2,s)
%XI
%    XI_I = XI(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:10

L_0 = in2(1,:);
deltaL = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = 1.0./L_0;
xi_i = [-phi.*t2;t2.*theta;0.0;0.0;0.0;t2.*(L_0+deltaL)];
end
