function omega_i_1_i = omega_rel(in1,in2,L_0)
%OMEGA_REL
%    OMEGA_I_1_I = OMEGA_REL(IN1,IN2,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:49:23

dphi = in2(2,:);
dtheta = in2(1,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = phi.^2;
t3 = phi.^3;
t4 = theta.^2;
t5 = theta.^3;
t6 = t2+t4;
t7 = 1.0./t6;
t9 = sqrt(t6);
t8 = t7.^2;
t10 = 1.0./t9;
t12 = cos(t9);
t13 = sin(t9);
t11 = t10.^3;
t14 = t12-1.0;
t15 = phi.*t7.*t12.*theta;
t16 = t10.*t13;
t17 = t2.*t7.*t12;
t18 = t4.*t7.*t12;
t19 = phi.*t7.*t14;
t20 = t7.*t14.*theta;
t21 = phi.*t11.*t13.*theta;
t22 = t2.*t11.*t13;
t23 = t4.*t11.*t13;
t31 = phi.*t4.*t8.*t14.*2.0;
t32 = t2.*t8.*t14.*theta.*2.0;
t24 = -t19;
t25 = -t20;
t26 = -t21;
t27 = phi.*t23;
t28 = t22.*theta;
t29 = -t22;
t30 = -t23;
t33 = t15+t26;
t36 = t16+t17+t29;
t37 = t16+t18+t30;
t40 = t24+t27+t31;
t41 = t25+t28+t32;
t34 = dphi.*t33;
t35 = dtheta.*t33;
t38 = dphi.*t36;
t39 = dtheta.*t37;
t42 = dtheta.*t40;
t43 = dphi.*t41;
t44 = t35+t38;
t45 = t34+t39;
t46 = t42+t43;
omega_i_1_i = [-t44.*(t2.*t7.*t14+1.0)+t24.*t45.*theta-phi.*t16.*(dphi.*phi.*t16+dtheta.*t16.*theta);t12.*t45+t16.*theta.*(dphi.*(t27+t31)+dtheta.*(t20.*-2.0+t5.*t8.*t14.*2.0+t5.*t11.*t13))+phi.*t16.*t46;-t46.*(t4.*t7.*t14+1.0)+t24.*theta.*(dtheta.*(t28+t32)+dphi.*(t19.*-2.0+t3.*t8.*t14.*2.0+t3.*t11.*t13))+t16.*t44.*theta];
end
