function v_par_i = v_par(in1,L_0)
%V_PAR
%    V_PAR_I = V_PAR(IN1,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:49:25

deltaL = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = phi.^2;
t4 = theta.^2;
t5 = t3+t4;
t6 = 1.0./t5;
t8 = sqrt(t5);
t7 = t6.^2;
t9 = 1.0./t8;
t11 = cos(t8);
t12 = sin(t8);
t10 = t9.^3;
t13 = t12.^2;
t14 = t11-1.0;
t16 = phi.*t2.*t6.*t11;
t17 = t2.*t6.*t11.*theta;
t15 = t14.^2;
t18 = phi.*t2.*t10.*t12;
t19 = t2.*t10.*t12.*theta;
t20 = t3.*t6.*t14;
t21 = t4.*t6.*t14;
t22 = t2.*t6.*t14;
t28 = t2.*t3.*t10.*t12;
t29 = t2.*t4.*t10.*t12;
t31 = phi.*t2.*t7.*t14.*theta.*2.0;
t32 = t2.*t3.*t7.*t14.*2.0;
t33 = t2.*t4.*t7.*t14.*2.0;
t23 = t18.*theta;
t24 = t20+1.0;
t25 = -t18;
t26 = t21+1.0;
t27 = -t19;
t30 = -t22;
t34 = t16+t25;
t35 = t17+t27;
t36 = t23+t31;
t38 = t28+t30+t32;
t39 = t29+t30+t33;
t37 = phi.*t6.*t14.*t36.*theta;
v_par_i = reshape([t37+t26.*t39-t9.*t12.*t35.*theta,t24.*t36-phi.*t9.*t12.*t35+phi.*t6.*t14.*t39.*theta,t11.*t35+phi.*t9.*t12.*t36+t9.*t12.*t39.*theta,t26.*t36-t9.*t12.*t34.*theta+phi.*t6.*t14.*t38.*theta,t37+t24.*t38-phi.*t9.*t12.*t34,t11.*t34+phi.*t9.*t12.*t38+t9.*t12.*t36.*theta,-t6.*t13.*theta-t3.*t7.*t15.*theta-t6.*t14.*t26.*theta,-phi.*t6.*t13-phi.*t4.*t7.*t15-phi.*t6.*t14.*t24,t9.*t11.*t12-t3.*t10.*t12.*t14-t4.*t10.*t12.*t14],[3,3]);
end
