function grad_int_dr_i = grad_int_dr(in1,in2)
%GRAD_INT_DR
%    GRAD_INT_DR_I = GRAD_INT_DR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:06

grad_int_dr_i = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
