function p_comi = p_com(in1,in2)
%P_COM
%    P_COMI = P_COM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:49:25

L_0 = in2(1,:);
deltaL = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = L_0+deltaL;
t3 = phi.^2;
t4 = theta.^2;
t5 = t3+t4;
t6 = 1.0./t5.^2;
t7 = sqrt(t5);
t8 = 1.0./t7.^3;
t9 = cos(t7);
t10 = sin(t7);
p_comi = [t2.*t8.*theta.*(t7-t10);phi.*t2.*t8.*(t7-t10);-(t2.*t10)./t7-t2.*1.0./t7.^2.*t9.*(t9-1.0)+t2.*t3.*t6.*t10.*(t7-t10)+t2.*t4.*t6.*t10.*(t7-t10)];
end
