function dv_i_1_i = a_rel(theta,dtheta,ddtheta,L_0)
%A_REL
%    DV_I_1_I = A_REL(THETA,DTHETA,DDTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

t2 = dtheta.^2;
t3 = theta./2.0;
t4 = theta./4.0;
t9 = theta./8.0;
t10 = theta./1.6e+1;
t5 = cos(t3);
t6 = cos(t4);
t7 = sin(t3);
t8 = sin(t4);
t11 = cos(t9);
t12 = cos(t10);
t13 = sin(t9);
t14 = sin(t10);
dv_i_1_i = [ddtheta.*(L_0.*t5.*t6.*t11.*t12.*(-1.0./2.0)+(L_0.*t6.*t7.*t11.*t14)./1.6e+1+(L_0.*t6.*t7.*t12.*t13)./8.0+(L_0.*t7.*t8.*t11.*t12)./4.0)+t2.*((L_0.*t5.*t6.*t11.*t14)./1.6e+1+(L_0.*t5.*t6.*t12.*t13)./8.0+(L_0.*t5.*t8.*t11.*t12)./4.0+L_0.*t6.*t7.*t11.*t12.*(8.5e+1./2.56e+2)-(L_0.*t6.*t7.*t13.*t14)./6.4e+1-(L_0.*t7.*t8.*t11.*t14)./3.2e+1-(L_0.*t7.*t8.*t12.*t13)./1.6e+1);0.0;-ddtheta.*((L_0.*t5.*t6.*t13)./8.0+(L_0.*t5.*t8.*t11)./4.0+(L_0.*t6.*t7.*t11)./2.0)+t2.*(L_0.*t5.*t6.*t11.*(-2.1e+1./6.4e+1)+(L_0.*t5.*t8.*t13)./1.6e+1+(L_0.*t6.*t7.*t13)./8.0+(L_0.*t7.*t8.*t11)./4.0)];
end
