function omega_i_1_i = omega_rel(theta,dtheta,L_0)
%OMEGA_REL
%    OMEGA_I_1_I = OMEGA_REL(THETA,DTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

omega_i_1_i = [0.0;-dtheta.*sin(theta).^2-dtheta.*cos(theta).^2;0.0];
end
