function omega_par_i = omega_par(theta,L_0)
%OMEGA_PAR
%    OMEGA_PAR_I = OMEGA_PAR(THETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

omega_par_i = [0.0;-cos(theta).^2-sin(theta).^2;0.0];
end
