function T_s = T_s(theta,in2,s)
%T_s
%    T_s = T_s(THETA,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

L_0 = in2(1,:);
t2 = 1.0./L_0;
t3 = s.*t2.*theta;
t4 = cos(t3);
t5 = sin(t3);
t6 = t3./2.0;
t7 = t3./4.0;
t9 = t3./8.0;
t8 = cos(t7);
t10 = cos(t9);
T_s = reshape([t4,0.0,t5,0.0,0.0,1.0,0.0,0.0,-t5,0.0,t4,0.0,-s.*t8.*t10.*cos(t3./1.6e+1).*sin(t6),0.0,s.*t8.*t10.*cos(t6),1.0],[4,4]);
end
