function v_par_i = v_par(theta,L_0)
%V_PAR
%    V_PAR_I = V_PAR(THETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

t2 = cos(theta);
t3 = sin(theta);
t4 = theta./2.0;
t5 = theta./4.0;
t10 = theta./8.0;
t11 = theta./1.6e+1;
t6 = cos(t4);
t7 = cos(t5);
t8 = sin(t4);
t9 = sin(t5);
t12 = cos(t10);
t13 = cos(t11);
t14 = sin(t10);
t15 = sin(t11);
t16 = (L_0.*t7.*t8.*t12)./2.0;
t17 = (L_0.*t6.*t9.*t12)./4.0;
t18 = (L_0.*t6.*t7.*t14)./8.0;
t19 = (L_0.*t6.*t7.*t12.*t13)./2.0;
t20 = (L_0.*t8.*t9.*t12.*t13)./4.0;
t22 = (L_0.*t7.*t8.*t13.*t14)./8.0;
t23 = (L_0.*t7.*t8.*t12.*t15)./1.6e+1;
t21 = -t19;
t24 = t16+t17+t18;
t25 = t20+t21+t22+t23;
v_par_i = [t2.*t25-t3.*t24;0.0;-t2.*t24-t3.*t25];
end
