function v_i_1_i = v_rel(theta,dtheta,L_0)
%V_REL
%    V_I_1_I = V_REL(THETA,DTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

t2 = theta./2.0;
t3 = theta./4.0;
t8 = theta./8.0;
t9 = theta./1.6e+1;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = sin(t3);
t10 = cos(t8);
t11 = cos(t9);
t12 = sin(t8);
v_i_1_i = [dtheta.*(L_0.*t4.*t5.*t10.*t11.*(-1.0./2.0)+(L_0.*t5.*t6.*t11.*t12)./8.0+(L_0.*t6.*t7.*t10.*t11)./4.0+(L_0.*t5.*t6.*t10.*sin(t9))./1.6e+1);0.0;-dtheta.*((L_0.*t4.*t5.*t12)./8.0+(L_0.*t4.*t7.*t10)./4.0+(L_0.*t5.*t6.*t10)./2.0)];
end
