function D_q = D(theta,dtheta,in3)
%D
%    D_q = D(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:57

E = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
R = in3(2,:);
D_q = (E.*Eta.*R.^4.*dtheta.*pi.*2.499999999999747e-1)./L_0;
end
