function int_ddr_i = int_ddr(theta,dtheta,ddtheta,in4)
%INT_DDR
%    INT_DDR_I = INT_DDR(THETA,DTHETA,DDTHETA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:51

int_ddr_i = [0.0;0.0;0.0];
end
