function p_comi = p_com(theta,in2)
%P_COM
%    P_COMI = P_COM(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:12:47

L_0 = in2(1,:);
R = in2(2,:);
rho = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta.*5.545614591379636e-2;
t5 = theta.*1.109122918275927e-1;
t6 = theta.*2.218245836551854e-1;
t7 = theta.*4.436491673103708e-1;
t8 = theta.*7.043854086203644e-3;
t9 = theta.*1.408770817240729e-2;
t10 = theta.*2.817541634481458e-2;
t11 = theta.*5.635083268962916e-2;
t12 = R.^2;
t21 = 1.0./pi;
t25 = 1.0./rho;
t26 = theta./2.0;
t27 = theta./4.0;
t32 = theta./8.0;
t33 = theta./1.6e+1;
t34 = theta./3.2e+1;
t13 = cos(t4);
t14 = cos(t5);
t15 = cos(t6);
t16 = cos(t7);
t17 = cos(t8);
t18 = cos(t9);
t19 = cos(t10);
t20 = cos(t11);
t22 = 1.0./t12;
t23 = sin(t7);
t24 = sin(t11);
t28 = cos(t26);
t29 = cos(t27);
t30 = sin(t26);
t31 = sin(t27);
t35 = cos(t32);
t36 = cos(t33);
t37 = cos(t34);
t38 = L_0.*rho.*t12.*t18.*t19.*t20.*pi.*6.261203632181017e-2;
t39 = L_0.*rho.*t12.*t14.*t15.*t16.*pi.*4.929435192337454e-1;
t40 = L_0.*rho.*t12.*t17.*t18.*t19.*t24.*pi.*6.261203632181017e-2;
t41 = L_0.*rho.*t12.*t13.*t14.*t15.*t23.*pi.*4.929435192337454e-1;
t42 = L_0.*rho.*t12.*t29.*t35.*t36.*pi.*4.444444444443434e-1;
t43 = L_0.*rho.*t12.*t31.*t35.*t36.*t37.*pi.*4.444444444443434e-1;
t44 = t38+t39+t42;
t45 = t40+t41+t43;
p_comi = [-L_0.*t3.*t28.*t29.*t35-(t2.*t21.*t22.*t25.*t45)./2.0+(t3.*t21.*t22.*t25.*t44)./2.0+L_0.*t2.*t29.*t30.*t35.*t36;0.0;-L_0.*t2.*t28.*t29.*t35+(t2.*t21.*t22.*t25.*t44)./2.0+(t3.*t21.*t22.*t25.*t45)./2.0-L_0.*t3.*t29.*t30.*t35.*t36];
end
