function grad_int_r_i_X_dr_i = grad_int_r_X_dr(theta,in2)
%grad_int_r_X_dr
%    grad_int_r_i_X_dr_i = grad_int_r_X_dr(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:47

L_0 = in2(1,:);
R = in2(2,:);
rho = in2(3,:);
grad_int_r_i_X_dr_i = [0.0,(L_0.^3.*R.^2.*rho.*1.0./theta.^4.*pi.*(cos(theta).*2.0+theta.^2-2.0))./2.0,0.0];
end
