function domega_i_1_i = domega_rel(theta,dtheta,ddtheta,in4)
%DOMEGA_REL
%    DOMEGA_I_1_I = DOMEGA_REL(THETA,DTHETA,DDTHETA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

domega_i_1_i = [0.0;0.0;ddtheta];
end
