function D_q = D(theta,dtheta,in3)
%D
%    D_q = D(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:47

E = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
R = in3(2,:);
D_q = (E.*Eta.*R.^4.*dtheta.*pi)./(L_0.*4.0);
end
