function dI = dI(theta,dtheta,in3)
%dI
%    dI = dI(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:46

dI = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
