function grad_J = grad_J(theta,in2)
%grad_J
%    grad_J = grad_J(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:47

L_0 = in2(1,:);
R = in2(2,:);
rho = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0.^3;
t5 = R.^2;
t6 = theta.*2.0;
t7 = theta.^2;
t10 = 1.0./theta.^3;
t12 = 1.0./theta.^5;
t8 = t2.^2;
t9 = t3.^2;
t11 = 1.0./t7.^2;
t13 = t2-1.0;
t14 = rho.*t2.*t4.*t5.*pi;
t15 = rho.*t3.*t4.*t5.*pi.*4.0;
t16 = rho.*t4.*t5.*pi.*(5.0./2.0);
t18 = t3.*t14.*4.0;
t19 = t3.*t7.*t14;
t20 = rho.*t4.*t5.*t8.*pi.*(7.0./2.0);
t21 = rho.*t4.*t5.*t9.*t10.*pi;
t22 = -t20;
t24 = t14+t16+t22;
t25 = t24.*theta;
t28 = t12.*(t15-t18+t19-t25);
grad_J = reshape([t21+t12.*t13.*t14.*4.0-rho.*t4.*t5.*t11.*pi.*(t6-sin(t6)).*(3.0./4.0)-rho.*t4.*t5.*t12.*t13.*pi.*4.0+rho.*t3.*t4.*t5.*t11.*t13.*pi.*2.0,0.0,t28,0.0,rho.*t4.*t5.*t10.*pi.*-2.0+rho.*t4.*t5.*t12.*pi.*sin(theta./2.0).^2.*1.6e+1-rho.*t3.*t4.*t5.*t11.*pi.*2.0,0.0,t28,0.0,-t21-t3.*t11.*t14.*(7.0./2.0)-(rho.*t4.*t5.*t10.*pi)./2.0+rho.*t4.*t5.*t9.*t12.*pi.*4.0],[3,3]);
end
