function int_r_i_X_dr_i = int_r_X_dr(theta,dtheta,in3)
%int_r_X_dr
%    int_r_i_X_dr_i = int_r_X_dr(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:46

L_0 = in3(1,:);
R = in3(2,:);
rho = in3(3,:);
int_r_i_X_dr_i = [0.0;(L_0.^3.*R.^2.*dtheta.*rho.*1.0./theta.^4.*pi.*(cos(theta).*2.0+theta.^2-2.0))./2.0;0.0];
end
