function J = J(theta,dtheta,in3)
%J
%    J = J(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:46

L_0 = in3(1,:);
R = in3(2,:);
rho = in3(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = L_0.^3;
t5 = R.^2;
t6 = theta.*2.0;
t7 = theta.*5.0;
t8 = theta.^2;
t12 = 1.0./theta.^5;
t9 = t2.^2;
t10 = sin(t6);
t11 = t3.^2;
t13 = t3.*8.0;
t15 = -t13;
t16 = t10.*4.0;
t17 = t9.*theta.*7.0;
t19 = t8.*t10;
t18 = -t17;
t20 = -t19;
t22 = (dtheta.*rho.*t4.*t5.*t12.*pi.*(t7+t15+t16+t18+t20+t2.*theta.*2.0))./2.0;
t23 = -t22;
J = reshape([dtheta.*rho.*t4.*t5.*t12.*pi.*(t2.*3.2e+1-t9.*1.6e+1+t8.*t9.*4.0+t6.*theta+t13.*theta-t2.*t3.*theta.*1.4e+1-1.6e+1).*(-1.0./4.0),0.0,t23,0.0,dtheta.*rho.*t4.*t5.*t12.*pi.*(t8+t3.*theta-sin(theta./2.0).^2.*8.0).*-2.0,0.0,t23,0.0,dtheta.*rho.*t4.*t5.*t12.*pi.*(t8-t11.*8.0+t10.*theta.*(7.0./2.0)+t6.*t11.*theta).*(-1.0./2.0)],[3,3]);
end
