function K_q = K(theta,in2)
%K
%    K_q = K(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:47

E = in2(4,:);
L_0 = in2(1,:);
R = in2(2,:);
K_q = (E.*R.^4.*theta.*pi)./(L_0.*4.0);
end
