function dv_i_comi = a_com_rel(theta,dtheta,ddtheta,in4)
%A_COM_REL
%    DV_I_COMI = A_COM_REL(THETA,DTHETA,DDTHETA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

dv_i_comi = [0.0;0.0;0.0];
end
