function grad_int_r_i_X_dr_i = grad_int_r_X_dr(theta,in2)
%grad_int_r_X_dr
%    grad_int_r_i_X_dr_i = grad_int_r_X_dr(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

grad_int_r_i_X_dr_i = [0.0,0.0,0.0];
end
