function int_pv_r_O_dd_r = int_pv_r_O_dd_r(theta,dtheta,ddtheta,in4)
%int_pv_r_O_dd_r
%    int_pv_r_O_dd_r = int_pv_r_O_dd_r(THETA,DTHETA,DDTHETA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

int_pv_r_O_dd_r = 0.0;
end
