function int_r_i_X_ddr_i = int_r_X_ddr(theta,dtheta,ddtheta,in4)
%int_r_X_ddr
%    int_r_i_X_ddr_i = int_r_X_ddr(THETA,DTHETA,DDTHETA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

int_r_i_X_ddr_i = [0.0;0.0;0.0];
end
