function int_dr_i_O_dr_i = int_dr_O_dr(theta,dtheta,in3)
%int_dr_O_dr
%    int_dr_i_O_dr_i = int_dr_O_dr(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

int_dr_i_O_dr_i = 0.0;
end
