function int_dr_i = int_dr(theta,dtheta,in3)
%INT_DR
%    INT_DR_I = INT_DR(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

int_dr_i = [0.0;0.0;0.0];
end
