function p_comi = p_com(theta,in2)
%P_COM
%    P_COMI = P_COM(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

pcom_1 = in2(5,:);
pcom_2 = in2(6,:);
pcom_3 = in2(7,:);
p_comi = [pcom_1;pcom_2;pcom_3];
end
