function xi_i = xi(theta,in2,s)
%XI
%    XI_I = XI(THETA,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

xi_i = [0.0;0.0;0.0;0.0;0.0;0.0];
end
