function T = T(theta,L_0)
%T
%    T = T(THETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:41

t2 = cos(theta);
t3 = sin(theta);
t4 = theta./8.0;
t5 = cos(t4);
t6 = t5.^2;
t7 = t6.*2.0;
t8 = t7-1.0;
T = reshape([t2,0.0,t3,0.0,0.0,1.0,0.0,0.0,-t3,0.0,t2,0.0,-L_0.*t5.*cos(theta./4.0).*cos(theta./1.6e+1).*sin(theta./2.0),0.0,L_0.*t5.*t8.*(t8.^2.*2.0-1.0),1.0],[4,4]);
end
