function T_s = T_s(theta,in2,s)
%T_s
%    T_s = T_s(THETA,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:41

L_0 = in2(1,:);
t2 = 1.0./L_0;
t3 = s.*t2.*theta;
t4 = cos(t3);
t5 = sin(t3);
t6 = t3./8.0;
t7 = cos(t6);
t8 = t7.^2;
t9 = t8.*2.0;
t10 = t9-1.0;
T_s = reshape([t4,0.0,t5,0.0,0.0,1.0,0.0,0.0,-t5,0.0,t4,0.0,-s.*t7.*cos(t3./4.0).*cos(t3./1.6e+1).*sin(t3./2.0),0.0,s.*t7.*t10.*(t10.^2.*2.0-1.0),1.0],[4,4]);
end
