function v_par_i = v_par(theta,L_0)
%V_PAR
%    V_PAR_I = V_PAR(THETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:41

t2 = cos(theta);
t3 = sin(theta);
t4 = theta./8.0;
t5 = theta./1.6e+1;
t6 = cos(t5);
t7 = sin(t4);
t8 = t6.^2;
t11 = t7.^2;
t9 = t8.^2;
t10 = t8.^3;
t12 = t11.^2;
t13 = t11.^3;
t15 = t8.^5;
t17 = t8.^7;
t19 = t11.*1.26e+2;
t21 = t8.*8.3e+1;
t14 = t9.^2;
t16 = t9.^3;
t18 = t13.*1.12e+2;
t20 = t12.*2.16e+2;
t23 = t9.*9.88e+2;
t24 = t10.*5.132e+3;
t26 = t17.*3.84e+3;
t29 = t15.*1.9072e+4;
t22 = -t20;
t27 = t14.*1.3568e+4;
t28 = t16.*1.3568e+4;
t30 = -t27;
t31 = -t28;
t32 = t18+t19+t22-2.1e+1;
v_par_i = [(L_0.*t3.*t7.*t32)./8.0-(L_0.*t2.*t6.*(t21-t23+t24+t26+t29+t30+t31-2.0))./2.0;0.0;(L_0.*t2.*t7.*t32)./8.0+(L_0.*t3.*t6.*(t21-t23+t24+t26+t29+t30+t31-2.0))./2.0];
end
