function T = T(in1,L_0)
%T
%    T = T(IN1,L_0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:59:28

deltaL = in1(6,:);
gamma_X = in1(4,:);
gamma_Y = in1(5,:);
kappa_X = in1(1,:);
kappa_Y = in1(2,:);
tau_Z = in1(3,:);
t2 = kappa_X.*kappa_Y;
t3 = kappa_X.*tau_Z;
t4 = kappa_Y.*tau_Z;
t5 = kappa_X.^2;
t6 = kappa_Y.^2;
t7 = tau_Z.^2;
t8 = t5+t6+t7;
t9 = 1.0./t8;
t10 = sqrt(t8);
t11 = 1.0./t10.^3;
t12 = cos(t10);
t13 = sin(t10);
t15 = t2.*t12;
t16 = t3.*t12;
t17 = t4.*t12;
t18 = t12-1.0;
t19 = kappa_X.*t10.*t13;
t20 = kappa_Y.*t10.*t13;
t21 = t10.*t13.*tau_Z;
mt1 = [t9.*t18.*(t5+t7)+1.0,t9.*(-t2+t15+t21),-t9.*(t4-t17+t19),0.0,-t9.*(t2-t15+t21),t9.*t18.*(t6+t7)+1.0,-t9.*(-t3+t16+t20),0.0,t9.*(-t4+t17+t19),t9.*(t3-t16+t20),t9.*t18.*(t5+t6)+1.0,0.0,gamma_X-t9.*t18.*(L_0.*kappa_X+deltaL.*kappa_X-gamma_Y.*tau_Z)-t11.*(t10-t13).*(L_0.*t4+deltaL.*t4+gamma_Y.*t2+gamma_X.*t5+gamma_X.*t7),gamma_Y-t9.*t18.*(L_0.*kappa_Y+deltaL.*kappa_Y+gamma_X.*tau_Z)-t11.*(t10-t13).*(-L_0.*t3-deltaL.*t3+gamma_X.*t2+gamma_Y.*t6+gamma_Y.*t7)];
mt2 = [L_0+deltaL+t9.*t18.*(gamma_X.*kappa_X+gamma_Y.*kappa_Y)-t11.*(t10-t13).*(L_0.*t5+L_0.*t6+deltaL.*t5+deltaL.*t6+gamma_X.*t4-gamma_Y.*t3),1.0];
T = reshape([mt1,mt2],4,4);
end
