function T_s = T_s(in1,in2,s)
%T_s
%    T_s = T_s(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:59:28

L_0 = in2(1,:);
deltaL = in1(6,:);
gamma_X = in1(4,:);
gamma_Y = in1(5,:);
kappa_X = in1(1,:);
kappa_Y = in1(2,:);
tau_Z = in1(3,:);
t2 = kappa_X.*kappa_Y;
t3 = kappa_X.*tau_Z;
t4 = kappa_Y.*tau_Z;
t5 = kappa_X.^2;
t6 = kappa_Y.^2;
t7 = tau_Z.^2;
t8 = 1.0./L_0;
t9 = t5+t6+t7;
t10 = 1.0./t9;
t11 = sqrt(t9);
t12 = 1.0./t11.^3;
t13 = s.*t11;
t15 = t8.*t13;
t16 = cos(t15);
t17 = sin(t15);
t18 = L_0.*t17;
t19 = t2.*t16;
t20 = t3.*t16;
t21 = t4.*t16;
t22 = t16-1.0;
t23 = kappa_X.*t11.*t17;
t24 = kappa_Y.*t11.*t17;
t25 = t11.*t17.*tau_Z;
mt1 = [t10.*t22.*(t5+t7)+1.0,t10.*(-t2+t19+t25),-t10.*(t4-t21+t23),0.0,-t10.*(t2-t19+t25),t10.*t22.*(t6+t7)+1.0,-t10.*(-t3+t20+t24),0.0,t10.*(-t4+t21+t23),t10.*(t3-t20+t24),t10.*t22.*(t5+t6)+1.0,0.0,-t10.*t22.*(L_0.*kappa_X+deltaL.*kappa_X-gamma_Y.*tau_Z)+gamma_X.*s.*t8-t8.*t12.*(t13-t18).*(L_0.*t4+deltaL.*t4+gamma_Y.*t2+gamma_X.*t5+gamma_X.*t7),-t10.*t22.*(L_0.*kappa_Y+deltaL.*kappa_Y+gamma_X.*tau_Z)+gamma_Y.*s.*t8-t8.*t12.*(t13-t18).*(-L_0.*t3-deltaL.*t3+gamma_X.*t2+gamma_Y.*t6+gamma_Y.*t7)];
mt2 = [t10.*t22.*(gamma_X.*kappa_X+gamma_Y.*kappa_Y)+s.*t8.*(L_0+deltaL)-t8.*t12.*(t13-t18).*(L_0.*t5+L_0.*t6+deltaL.*t5+deltaL.*t6+gamma_X.*t4-gamma_Y.*t3),1.0];
T_s = reshape([mt1,mt2],4,4);
end
