function I = I(theta,in2)
%I
%    I = I(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

I_1_1 = in2(8,:);
I_1_2 = in2(11,:);
I_1_3 = in2(12,:);
I_2_2 = in2(9,:);
I_2_3 = in2(13,:);
I_3_3 = in2(10,:);
I = reshape([I_1_1,I_1_2,I_1_3,I_1_2,I_2_2,I_2_3,I_1_3,I_2_3,I_3_3],[3,3]);
end
