function v_i_comi = v_com_rel(theta,dtheta,in3)
%V_COM_REL
%    V_I_COMI = V_COM_REL(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

v_i_comi = [0.0;0.0;0.0];
end
