function omega_par_i = omega_par(theta,in2)
%OMEGA_PAR
%    OMEGA_PAR_I = OMEGA_PAR(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

alpha_ = in2(1,:);
omega_par_i = [0.0;sin(alpha_);cos(alpha_)];
end
