function omega_i_1_i = omega_rel(theta,dtheta,in3)
%OMEGA_REL
%    OMEGA_I_1_I = OMEGA_REL(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:46

omega_i_1_i = [0.0;0.0;dtheta];
end
