function v_par_i = v_par(theta,in2)
%V_PAR
%    V_PAR_I = V_PAR(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

a_ = in2(2,:);
alpha_ = in2(1,:);
v_par_i = [0.0;a_.*cos(alpha_);-a_.*sin(alpha_)];
end
