function D_s = D_s(theta,dtheta,in3,s)
%D_s
%    D_s = D_s(THETA,DTHETA,IN3,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:38

E = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
R = in3(2,:);
D_s = (E.*Eta.*1.0./L_0.^2.*R.^4.*dtheta.*pi)./4.0;
end
