function grad_int_dr_i = grad_int_dr(theta,in2)
%GRAD_INT_DR
%    GRAD_INT_DR_I = GRAD_INT_DR(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:42

grad_int_dr_i = [0.0,0.0,0.0];
end
