function int_dr_i = int_dr(theta,dtheta,in3)
%INT_DR
%    INT_DR_I = INT_DR(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:41

int_dr_i = [0.0;0.0;0.0];
end
