function K_s = K_s(theta,in2,s)
%K_s
%    K_s = K_s(THETA,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:38

E = in2(4,:);
L_0 = in2(1,:);
R = in2(2,:);
K_s = (E.*1.0./L_0.^2.*R.^4.*theta.*pi)./4.0;
end
