function m = m(in1)
%M
%    M = M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:41

L_0 = in1(1,:);
R = in1(2,:);
rho = in1(3,:);
m = L_0.*R.^2.*rho.*pi;
end
