function p_i = p_i_s(theta,in2,s)
%P_I_S
%    P_I = P_I_S(THETA,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:36

L_0 = in2(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./L_0;
t5 = theta./2.0;
t6 = theta./4.0;
t9 = theta./8.0;
t10 = theta./1.6e+1;
t7 = cos(t6);
t8 = sin(t5);
t11 = cos(t9);
t12 = cos(t10);
t14 = s.*t4.*t5;
t15 = s.*t4.*t6;
t18 = s.*t4.*t9;
t19 = s.*t4.*t10;
t13 = t11.^2;
t16 = cos(t15);
t17 = sin(t14);
t21 = cos(t18);
t22 = cos(t19);
t20 = t13.*2.0;
t24 = t21.^2;
t23 = t20-1.0;
t25 = t24.*2.0;
t26 = t25-1.0;
t27 = t26.^2;
t28 = t27.*2.0;
t29 = t28-1.0;
p_i = [-L_0.*t7.*t8.*t11.*(t2-t2.*t12+1.0)+s.*t3.*t21.*t26.*t29-s.*t2.*t16.*t17.*t21.*t22;0.0;-L_0.*t2.*t11.*t23.*(t23.^2.*2.0-1.0)+s.*t2.*t21.*t26.*t29+s.*t3.*t16.*t17.*t21.*t22-L_0.*t3.*t7.*t8.*t11.*t12];
end
