function rho_L = rho_L_s(in1,s)
%rho_L_s
%    rho_L = rho_L_s(IN1,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Oct-2023 18:22:37

R = in1(2,:);
rho = in1(3,:);
rho_L = R.^2.*rho.*pi;
end
