function int_dr_i_X_pv_r = int_dr_X_pv_r(theta,dtheta,in3)
%int_dr_X_pv_r
%    int_dr_i_X_pv_r = int_dr_X_pv_r(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:46

int_dr_i_X_pv_r = [0.0,0.0,0.0];
end
