function p_comi = p_com(theta,in2)
%P_COM
%    P_COMI = P_COM(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:46

L_0 = in2(1,:);
t2 = 1.0./theta.^2;
p_comi = [-L_0.*t2.*(theta-sin(theta));0.0;L_0.*t2.*(cos(theta)-1.0)];
end
