function grad_v_com_i = grad_v_com(theta,in2)
%GRAD_V_COM
%    GRAD_V_COM_I = GRAD_V_COM(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

grad_v_com_i = [0.0,0.0,0.0];
end
