function int_ddr_i = int_ddr(theta,dtheta,ddtheta,in4)
%INT_DDR
%    INT_DDR_I = INT_DDR(THETA,DTHETA,DDTHETA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

int_ddr_i = [0.0;0.0;0.0];
end
