function int_r_i_X_dr_i = int_r_X_dr(theta,dtheta,in3)
%int_r_X_dr
%    int_r_i_X_dr_i = int_r_X_dr(THETA,DTHETA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:47

int_r_i_X_dr_i = [0.0;0.0;0.0];
end
