function K_q = K(in1,in2)
%K
%    K_q = K(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jul-2023 11:50:10

E = in2(4,:);
L_0 = in2(1,:);
R = in2(2,:);
deltaL = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = R.^4;
t3 = 1.0./L_0;
K_q = [E.*t2.*t3.*theta.*pi.*2.500000000000111e-1;E.*phi.*t2.*t3.*pi.*2.500000000000111e-1;E.*R.^2.*pi.*(t3.*(L_0+deltaL)-1.0).*1.000000000000044];
end
