function dv_i_1_i = a_rel(theta,dtheta,ddtheta,L_0)
%A_REL
%    DV_I_1_I = A_REL(THETA,DTHETA,DDTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:45

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./theta;
t4 = t2.*theta;
t5 = t3.*theta;
t7 = t6.^2;
t8 = t6.^3;
t9 = -t4;
t11 = t2+t5-1.0;
t10 = t3+t9;
dv_i_1_i = [-dtheta.*(L_0.*dtheta.*t2.*t6-L_0.*dtheta.*t8.*t11.*2.0)-L_0.*ddtheta.*t7.*t11;0.0;-dtheta.*(L_0.*dtheta.*t3.*t6-L_0.*dtheta.*t8.*t10.*2.0)-L_0.*ddtheta.*t7.*t10];
end
