function domega_i_1_i = domega_rel(theta,dtheta,ddtheta,L_0)
%DOMEGA_REL
%    DOMEGA_I_1_I = DOMEGA_REL(THETA,DTHETA,DDTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:45

domega_i_1_i = [0.0;-ddtheta;0.0];
end
