function omega_i_1_i = omega_rel(theta,dtheta,L_0)
%OMEGA_REL
%    OMEGA_I_1_I = OMEGA_REL(THETA,DTHETA,L_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:45

omega_i_1_i = [0.0;-dtheta;0.0];
end
