function T_s = T_s(theta,in2,s)
%T_s
%    T_s = T_s(THETA,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Nov-2023 16:39:45

L_0 = in2(1,:);
t2 = 1.0./L_0;
t3 = 1.0./theta;
t4 = s.*t2.*theta;
t5 = cos(t4);
t6 = sin(t4);
T_s = reshape([t5,0.0,t6,0.0,0.0,1.0,0.0,0.0,-t6,0.0,t5,0.0,L_0.*t3.*(t5-1.0),0.0,L_0.*t3.*t6,1.0],[4,4]);
end
