function D_s = D_s(in1,in2,in3,s)
%D_s
%    D_s = D_s(IN1,IN2,IN3,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:13:04

E_mod = in3(4,:);
Eta = in3(6,:);
L_0 = in3(1,:);
R = in3(2,:);
ddeltaL = in2(5,:);
dtheta_X_1 = in2(1,:);
dtheta_X_2 = in2(2,:);
dtheta_Y_1 = in2(3,:);
dtheta_Y_2 = in2(4,:);
t2 = R.^4;
t3 = 1.0./L_0;
t4 = t3.^2;
t5 = dtheta_X_1.*t3;
t6 = dtheta_Y_1.*t3;
t7 = dtheta_X_2.*s.*t4;
t8 = dtheta_Y_2.*s.*t4;
t9 = t5+t7;
t10 = t6+t8;
D_s = [(E_mod.*Eta.*t2.*t3.*t9.*pi)./4.0;(E_mod.*Eta.*s.*t2.*t4.*t9.*pi)./4.0;(E_mod.*Eta.*t2.*t3.*t10.*pi)./4.0;(E_mod.*Eta.*s.*t2.*t4.*t10.*pi)./4.0;E_mod.*Eta.*R.^2.*ddeltaL.*t4.*pi];
end
