function dI = dI(in1,in2,in3)
%dI
%    dI = dI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:18:14

dI = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
