function grad_int_dr_i = grad_int_dr(in1,in2)
%GRAD_INT_DR
%    GRAD_INT_DR_I = GRAD_INT_DR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:18:14

grad_int_dr_i = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,3]);
end
