function int_ddr_i = int_ddr(in1,in2,in3,in4)
%INT_DDR
%    INT_DDR_I = INT_DDR(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:18:14

int_ddr_i = [0.0;0.0;0.0];
end
