function int_dr_i = int_dr(in1,in2,in3)
%INT_DR
%    INT_DR_I = INT_DR(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:18:14

int_dr_i = [0.0;0.0;0.0];
end
