function K_s = K_s(in1,in2,s)
%K_s
%    K_s = K_s(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:13:04

E_mod = in2(4,:);
L_0 = in2(1,:);
R = in2(2,:);
deltaL = in1(5,:);
theta_X_1 = in1(1,:);
theta_X_2 = in1(2,:);
theta_Y_1 = in1(3,:);
theta_Y_2 = in1(4,:);
t2 = R.^4;
t3 = 1.0./L_0;
t4 = t3.^2;
t5 = t3.*theta_X_1;
t6 = t3.*theta_Y_1;
t7 = s.*t4.*theta_X_2;
t8 = s.*t4.*theta_Y_2;
t9 = t5+t7;
t10 = t6+t8;
K_s = [(E_mod.*t2.*t3.*t9.*pi)./4.0;(E_mod.*s.*t2.*t4.*t9.*pi)./4.0;(E_mod.*t2.*t3.*t10.*pi)./4.0;(E_mod.*s.*t2.*t4.*t10.*pi)./4.0;E_mod.*R.^2.*t3.*pi.*(t3.*(L_0+deltaL)-1.0)];
end
