function rho_L = rho_L_s(in1,s)
%rho_L_s
%    rho_L = rho_L_s(IN1,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:11:09

R = in1(2,:);
rho = in1(3,:);
rho_L = R.^2.*rho.*pi;
end
