function xi_i = xi(in1,in2,s)
%XI
%    XI_I = XI(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Aug-2023 10:18:14

L_0 = in2(1,:);
deltaL = in1(5,:);
theta_X_1 = in1(1,:);
theta_X_2 = in1(2,:);
theta_Y_1 = in1(3,:);
theta_Y_2 = in1(4,:);
t2 = 1.0./L_0;
t3 = t2.^2;
xi_i = [-t2.*theta_Y_1-s.*t3.*theta_Y_2;t2.*theta_X_1+s.*t3.*theta_X_2;0.0;0.0;0.0;t2.*(L_0+deltaL)];
end
